### ISSUE TITLE
Date pickers not working in Chrome on Windows

### ISSUE THREAD

**Issue by AshleyJBartlett** [aurelia-ui-toolkits/aurelia-mdc-web#48]
Date pickers don't seem to work in Chrome on Windows but they work in Firefox.

https://aurelia-ui-toolkits.github.io/aurelia-mdc-web/#/text-field/examples

Google Chrome version:
![image](https://user-images.githubusercontent.com/7014380/114428528-388b3d80-9bb4-11eb-88d2-7f4528cc780c.png)

**Comment by MaximBalaganskiy** [comment]
The MDC team has hidden the selector button in Chrome.
```scss
    &::-webkit-calendar-picker-indicator {
      display: none;
    }
```
